
name: angular

on:
  push:
    branches: [ "main" ]
    paths:
      - angular/**
  workflow_dispatch:

jobs:
  frontbuild:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
        - name: Get current time of build
          uses: gerred/actions/current-time@master
          id: current-time
        - name: Checkout
          uses: actions/checkout@v2  
        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'npm'
        - name: Install
          working-directory: angular/
          run: npm ci
        - name: Run Test
          working-directory: angular/
          run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless  
        - name: Run build
          working-directory: angular/
          run: npm run build     
        - name: Login to github registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: get build number
          uses: benjlevesque/short-sha@v1.2
          id: short-sha
          with:
           length: 7
        - name : build docker image and push
          uses: docker/build-push-action@v3
          with:
            context: .
            file: angular/Dockerfile
            push: true
            tags: |
              ghcr.io/${{ github.repository }}/${{ github.workflow }}/iotfrontend:${{ steps.short-sha.outputs.sha }}
        - name: Get git commit data
          uses: rlespinasse/git-commit-data-action@v1               
        - name: Send notification
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{ secrets.EMAIL_SENDER_USERNAME }}
            password: ${{ secrets.EMAIL_SENDER_PASSWORD }}
            subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
            body: ${{ github.job }} job in workflow ${{ github.workflow }} of ${{ github.repository }} of backend has ${{ job.status }} 
            to: ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
            from: ${{ env.GIT_COMMIT_AUTHOR }}"  

  

