name: occlient
on:
  push:
    tags:
      - "*.*.*"
    branches: [ "main" ]
    paths:
      - occlient/**
  pull_request:
    branches: [ "main" ]
    paths:
      - occlient/**
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: metaocclient
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/occlient
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
      - name: Build occlient
        uses: docker/build-push-action@v3
        with:
          context: .
          file: occlient/Dockerfile
          push: true
          tags: ${{ steps.metaocclient.outputs.tags }}