name: watcher
on:
  push:
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "main" ]
    paths:
      - watcher/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker meta
        id: metawatcher
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/watcher
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha 
      - name: Build watcher
        uses: docker/build-push-action@v3
        with:
          context: .
          file: watcher/Dockerfile
          push: true
          tags: ${{ steps.metawatcher.outputs.tags }}